# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

# commands to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libasound-dev
  - sudo apt-get install -y libjack-dev

install: pip install -r requirements-dev.txt

# command to run tests, e.g. python setup.py test
script: make test
